---
- name: Check for data-shared directory on control host
  ansible.builtin.stat:
    path: "{{ data_shared_src }}"
  delegate_to: localhost
  become: false
  run_once: true
  register: data_shared_stat

- name: Fail if data-shared is missing
  ansible.builtin.fail:
    msg: "Missing data-shared directory at {{ data_shared_src }}"
  when: not data_shared_stat.stat.exists

- name: Create /data-shared
  ansible.builtin.file:
    path: /data-shared
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy data-shared to server
  ansible.builtin.copy:
    src: "{{ data_shared_src }}/"
    dest: /data-shared/
    owner: root
    group: root
    mode: "0644"
    directory_mode: "0755"

- name: Find data-shared directories
  ansible.builtin.find:
    paths: /data-shared
    file_type: directory
  register: data_shared_dirs

- name: Find data-shared files
  ansible.builtin.find:
    paths: /data-shared
    file_type: file
  register: data_shared_files

- name: Fix permissions on data-shared directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "0755"
  loop: "{{ data_shared_dirs.files }}"

- name: Fix permissions on data-shared files
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ data_shared_files.files }}"
