---
- name: Ensure /etc/skel/.bashrc exists
  ansible.builtin.file:
    path: /etc/skel/.bashrc
    state: touch

- name: Add shell defaults to /etc/skel/.bashrc
  ansible.builtin.blockinfile:
    path: /etc/skel/.bashrc
    marker: "# {mark} ngs-course defaults"
    block: |
      force_color_prompt=yes
      alias ll='ls -l'
      export LC_ALL=C
      export MANWIDTH=120
      alias wgets='H="--header"; wget $H="Accept-Language: en-us,en;q=0.5" $H="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" $H="Connection: keep-alive" -U "Mozilla/5.0 (Windows NT 5.1; rv:10.0.2) Gecko/20100101 Firefox/10.0.2" --referer=/ '

- name: Install screen defaults
  ansible.builtin.copy:
    dest: /etc/skel/.screenrc
    mode: "0644"
    content: |
      hardstatus alwayslastline
      hardstatus string '%{= kG}[%{G}%H%? %1`%?%{g}][%= %{= kw}%-w%{+b yk} %n*%t%?(%u)%? %{-}%+w %=%{g}][%{B}%d.%m. %{W}%c%{g}]'

      defscrollback 20000

      startup_message off

- name: Install MOTD
  ansible.builtin.copy:
    dest: /etc/motd
    mode: "0644"
    src: motd
