---
- name: Install /etc/skel/.bashrc
  ansible.builtin.copy:
    src: "{{ contents_root }}/etc/skel/.bashrc"
    dest: /etc/skel/.bashrc
    mode: "0644"

- name: Install /etc/skel/.screenrc
  ansible.builtin.copy:
    src: "{{ contents_root }}/etc/skel/.screenrc"
    dest: /etc/skel/.screenrc
    mode: "0644"

- name: Install MOTD
  ansible.builtin.copy:
    src: "{{ contents_root }}/etc/motd"
    dest: /etc/motd
    mode: "0644"
